run:
  go: '1.23'
  build-tags:
    - cgo

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

issues:
  exclude-use-default: false
  exclude-dirs:
    - test
    - test.bak
  exclude-files:
    - ".*\\.pb\\.go$"
